site_name: ckanext-harvest-basket
site_url: https://datashades.github.io/ckanext-harvest-basket/
repo_url:  https://github.com/DataShades/ckanext-harvest-basket

markdown_extensions:
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
            alternate_style: true

plugins:
    - exclude:
        glob:
          - harvesters/snippets/*
    - include-markdown:
    - search:
        separator: '[\s\-\.\_]+'
    - mkdocstrings:
        handlers:
          python:
            paths: ["ckanext"]
            options:
              show_root_full_path: false
              show_root_heading: true
              # show_root_toc_entry: true
              show_symbol_type_heading: true
              show_source: false
              docstring_section_style: spacy

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate

nav:
  - index.md
  - installation.md
  - configuration.md
  - source_preview.md
  - Harvesters:
    - harvesters/base.md
    - harvesters/ArcGIS.md
    - harvesters/CKAN.md
    - harvesters/CSIRO.md
    - harvesters/CSW.md
    - harvesters/DCAT_JSON.md
    - harvesters/DKAN.md
    - harvesters/Junar.md
    - harvesters/ODS.md
    - harvesters/Socrata.md
  - troubleshooting.md

watch:
  - README.md
  - ckanext/harvest_basket
